[2024-07-15T23:10:08.150+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-07-15T23:10:08.164+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-15T23:10:08.171+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-07-15T23:10:08.175+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-07-15T23:10:08.177+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [queued]> from DB
[2024-07-15T23:10:08.184+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-15T23:10:08.185+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-15T23:10:08.188+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-15T23:10:08.188+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-15T23:10:08.188+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [queued]>
[2024-07-15T23:10:08.189+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-15T23:10:08.192+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-15T23:10:08.192+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-15T23:10:08.192+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-15T23:10:08.192+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [queued]>
[2024-07-15T23:10:08.192+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-07-15T23:10:08.197+0000] {taskinstance.py:1327} INFO - Executing <Task(DbtSeedOperator): dbt_seed> on 2024-07-15 23:10:03.352299+00:00
[2024-07-15T23:10:08.199+0000] {standard_task_runner.py:57} INFO - Started process 992 to run task
[2024-07-15T23:10:08.200+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_init_tasks', 'dbt_seed', 'manual__2024-07-15T23:10:03.352299+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_init_tasks.py', '--cfg-path', '/tmp/tmp4bfsw4ie']
[2024-07-15T23:10:08.201+0000] {standard_task_runner.py:85} INFO - Job 79: Subtask dbt_seed
[2024-07-15T23:10:08.201+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0xffff7f47a550>]
[2024-07-15T23:10:08.224+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-07-15T23:10:08.228+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [running]> on host b91763c3682d
[2024-07-15T23:10:08.229+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 992)
[2024-07-15T23:10:08.229+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 992)
[2024-07-15T23:10:08.229+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-15T23:10:08.230+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [running]> from DB
[2024-07-15T23:10:08.249+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-07-15T23:10:08.252+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-07-15T23:10:08.264+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-15T23:10:08.270+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_init_tasks' AIRFLOW_CTX_TASK_ID='dbt_seed' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T23:10:03.352299+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-15T23:10:03.352299+00:00'
[2024-07-15T23:10:08.271+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-07-15T23:10:08.271+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-07-15T23:10:08.271+0000] {dbt_hook.py:117} INFO - /home/airflow/.local/bin/dbt seed
[2024-07-15T23:10:08.274+0000] {dbt_hook.py:126} INFO - Output:
[2024-07-15T23:10:09.304+0000] {dbt_hook.py:130} INFO - [0m23:10:09  Running with dbt=1.8.3
[2024-07-15T23:10:09.441+0000] {dbt_hook.py:130} INFO - [0m23:10:09  Registered adapter: ***=1.8.2
[2024-07-15T23:10:09.549+0000] {dbt_hook.py:130} INFO - [0m23:10:09  Unable to do partial parsing because a project dependency has been added
[2024-07-15T23:10:10.315+0000] {dbt_hook.py:130} INFO - [0m23:10:10  Encountered an error:
[2024-07-15T23:10:10.315+0000] {dbt_hook.py:130} INFO - Compilation Error
[2024-07-15T23:10:10.315+0000] {dbt_hook.py:130} INFO -   Model 'model.matt_demo.crm_performance' (models/crm_sales_data/analysis/crm_performance.sql) depends on a node named 'stg_sales_pipeline' which was not found
[2024-07-15T23:10:11.544+0000] {dbt_hook.py:132} INFO - Command exited with return code 2
[2024-07-15T23:10:11.544+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [running]> from DB
[2024-07-15T23:10:11.552+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_dbt/operators/dbt_operator.py", line 135, in execute
    self.create_hook().run_cli('seed')
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2024-07-15T23:10:11.553+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_init_tasks.dbt_seed manual__2024-07-15T23:10:03.352299+00:00 [running]> from DB
[2024-07-15T23:10:11.554+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 3.365577
[2024-07-15T23:10:11.555+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-07-15T23:10:11.555+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=run_dbt_init_tasks, task_id=dbt_seed, execution_date=20240715T231003, start_date=20240715T231008, end_date=20240715T231011
[2024-07-15T23:10:11.562+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-07-15T23:10:11.563+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 79 for task dbt_seed (dbt command failed; 992)
[2024-07-15T23:10:11.578+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-15T23:10:11.588+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_init_tasks @ 2024-07-15 23:10:03.352299+00:00: manual__2024-07-15T23:10:03.352299+00:00, state:running, queued_at: 2024-07-15 23:10:03.359180+00:00. externally triggered: True>: 4 task(s)
[2024-07-15T23:10:11.588+0000] {dagrun.py:718} DEBUG - number of scheduleable tasks for <DagRun run_dbt_init_tasks @ 2024-07-15 23:10:03.352299+00:00: manual__2024-07-15T23:10:03.352299+00:00, state:running, queued_at: 2024-07-15 23:10:03.359180+00:00. externally triggered: True>: 3 task(s)
[2024-07-15T23:10:11.588+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.model.ecomm_demo.dim_date manual__2024-07-15T23:10:03.352299+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-15T23:10:11.588+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.model.ecomm_demo.dim_date manual__2024-07-15T23:10:03.352299+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-15T23:10:11.588+0000] {taskinstance.py:899} DEBUG - Setting task state for <TaskInstance: run_dbt_init_tasks.model.ecomm_demo.dim_date manual__2024-07-15T23:10:03.352299+00:00 [None]> to upstream_failed
[2024-07-15T23:10:11.589+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.model.ecomm_demo.dim_date manual__2024-07-15T23:10:03.352299+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1), upstream_task_ids={'dbt_seed'}
[2024-07-15T23:10:11.589+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_init_tasks.model.ecomm_demo.dim_date manual__2024-07-15T23:10:03.352299+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1), upstream_task_ids={'dbt_seed'}
[2024-07-15T23:10:11.589+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.test.ecomm_demo.dim_date manual__2024-07-15T23:10:03.352299+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-15T23:10:11.589+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.test.ecomm_demo.dim_date manual__2024-07-15T23:10:03.352299+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-15T23:10:11.589+0000] {taskinstance.py:899} DEBUG - Setting task state for <TaskInstance: run_dbt_init_tasks.test.ecomm_demo.dim_date manual__2024-07-15T23:10:03.352299+00:00 [None]> to upstream_failed
[2024-07-15T23:10:11.589+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.test.ecomm_demo.dim_date manual__2024-07-15T23:10:03.352299+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.ecomm_demo.dim_date', 'dbt_seed'}
[2024-07-15T23:10:11.589+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_init_tasks.test.ecomm_demo.dim_date manual__2024-07-15T23:10:03.352299+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.ecomm_demo.dim_date', 'dbt_seed'}
[2024-07-15T23:10:11.590+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.generate_dbt_docs manual__2024-07-15T23:10:03.352299+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-15T23:10:11.590+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.generate_dbt_docs manual__2024-07-15T23:10:03.352299+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-15T23:10:11.590+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_init_tasks.generate_dbt_docs manual__2024-07-15T23:10:03.352299+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'model.ecomm_demo.dim_date', 'test.ecomm_demo.dim_date'}
[2024-07-15T23:10:11.590+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_init_tasks.generate_dbt_docs manual__2024-07-15T23:10:03.352299+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'model.ecomm_demo.dim_date', 'test.ecomm_demo.dim_date'}
[2024-07-15T23:10:11.592+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
