[2024-06-29T21:41:10.715+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:41:10.726+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-02T00:10:00+00:00 [queued]>
[2024-06-29T21:41:10.728+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-02T00:10:00+00:00 [queued]>
[2024-06-29T21:41:10.729+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:41:10.733+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-02 00:10:00+00:00
[2024-06-29T21:41:10.735+0000] {standard_task_runner.py:63} INFO - Started process 2152 to run task
[2024-06-29T21:41:10.736+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-02T00:10:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpp4kckn2b']
[2024-06-29T21:41:10.737+0000] {standard_task_runner.py:91} INFO - Job 147: Subtask generate_and_insert_data
[2024-06-29T21:41:10.754+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-02T00:10:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:41:10.784+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T00:10:00+00:00'
[2024-06-29T21:41:10.784+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:41:10.840+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:41:10.840+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:41:10.840+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:41:10.840+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:41:10.841+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:41:10.846+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-02T00:10:00+00:00, execution_date=20230102T001000, start_date=20240629T214110, end_date=20240629T214110
[2024-06-29T21:41:10.888+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:41:10.895+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:41:10.896+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:04:59.784+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:04:59.795+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-02T00:10:00+00:00 [queued]>
[2024-06-29T22:04:59.797+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-02T00:10:00+00:00 [queued]>
[2024-06-29T22:04:59.797+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:04:59.802+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-02 00:10:00+00:00
[2024-06-29T22:04:59.804+0000] {standard_task_runner.py:63} INFO - Started process 2152 to run task
[2024-06-29T22:04:59.805+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-02T00:10:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp40znuolp']
[2024-06-29T22:04:59.806+0000] {standard_task_runner.py:91} INFO - Job 147: Subtask generate_and_insert_data
[2024-06-29T22:04:59.823+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-02T00:10:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:04:59.853+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T00:10:00+00:00'
[2024-06-29T22:04:59.853+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:04:59.911+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:04:59.911+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:04:59.911+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:04:59.912+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:04:59.912+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:04:59.917+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-02T00:10:00+00:00, execution_date=20230102T001000, start_date=20240629T220459, end_date=20240629T220459
[2024-06-29T22:04:59.947+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:04:59.954+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:04:59.955+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
