[2024-06-29T21:41:06.687+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:41:06.698+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T23:50:00+00:00 [queued]>
[2024-06-29T21:41:06.700+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T23:50:00+00:00 [queued]>
[2024-06-29T21:41:06.701+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:41:06.705+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 23:50:00+00:00
[2024-06-29T21:41:06.707+0000] {standard_task_runner.py:63} INFO - Started process 2116 to run task
[2024-06-29T21:41:06.709+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T23:50:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpml5ibpxg']
[2024-06-29T21:41:06.709+0000] {standard_task_runner.py:91} INFO - Job 145: Subtask generate_and_insert_data
[2024-06-29T21:41:06.729+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T23:50:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:41:06.761+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T23:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T23:50:00+00:00'
[2024-06-29T21:41:06.762+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:41:06.822+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:41:06.822+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:41:06.822+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:41:06.822+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:41:06.823+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:41:06.828+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T23:50:00+00:00, execution_date=20230101T235000, start_date=20240629T214106, end_date=20240629T214106
[2024-06-29T21:41:06.854+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:41:06.862+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:41:06.863+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:04:56.273+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:04:56.284+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T23:50:00+00:00 [queued]>
[2024-06-29T22:04:56.286+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T23:50:00+00:00 [queued]>
[2024-06-29T22:04:56.287+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:04:56.291+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 23:50:00+00:00
[2024-06-29T22:04:56.293+0000] {standard_task_runner.py:63} INFO - Started process 2116 to run task
[2024-06-29T22:04:56.294+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T23:50:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpg_rqe68s']
[2024-06-29T22:04:56.295+0000] {standard_task_runner.py:91} INFO - Job 145: Subtask generate_and_insert_data
[2024-06-29T22:04:56.313+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T23:50:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:04:56.343+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T23:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T23:50:00+00:00'
[2024-06-29T22:04:56.344+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:04:56.402+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:04:56.402+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:04:56.402+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:04:56.403+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:04:56.403+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:04:56.408+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T23:50:00+00:00, execution_date=20230101T235000, start_date=20240629T220456, end_date=20240629T220456
[2024-06-29T22:04:56.443+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:04:56.451+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:04:56.451+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
