[2024-07-06T18:55:42.844+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_main_data.export_and_load_user_data scheduled__2024-07-06T04:00:00+00:00 [queued]>
[2024-07-06T18:55:42.848+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_main_data.export_and_load_user_data scheduled__2024-07-06T04:00:00+00:00 [queued]>
[2024-07-06T18:55:42.848+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2024-07-06T18:55:42.852+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): export_and_load_user_data> on 2024-07-06 04:00:00+00:00
[2024-07-06T18:55:42.853+0000] {standard_task_runner.py:57} INFO - Started process 1834 to run task
[2024-07-06T18:55:42.855+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'import_main_data', 'export_and_load_user_data', 'scheduled__2024-07-06T04:00:00+00:00', '--job-id', '932', '--raw', '--subdir', 'DAGS_FOLDER/import_raw_data.py', '--cfg-path', '/tmp/tmpebtdxhok']
[2024-07-06T18:55:42.855+0000] {standard_task_runner.py:85} INFO - Job 932: Subtask export_and_load_user_data
[2024-07-06T18:55:42.876+0000] {task_command.py:410} INFO - Running <TaskInstance: import_main_data.export_and_load_user_data scheduled__2024-07-06T04:00:00+00:00 [running]> on host f6bf59d3e65b
[2024-07-06T18:55:42.917+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_main_data' AIRFLOW_CTX_TASK_ID='export_and_load_user_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-06T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-06T04:00:00+00:00'
[2024-07-06T18:55:42.918+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-06T18:55:42.918+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        LAST_TRANSFER=$(psql ***ql://***:***@company_dw:5432/company_dw -t -c "SELECT last_transfer FROM ops.last_transfer WHERE table_name = \'users\'")\n        psql ***ql://***:***@company_db:5432/company_db -c "\\copy (SELECT * FROM users WHERE created_at > \'$LAST_TRANSFER\') TO stdout" | psql ***ql://***:***@company_dw:5432/company_dw -c "\n        CREATE TEMP TABLE temp_users (LIKE raw.users INCLUDING DEFAULTS);\n        \\copy temp_users FROM stdin;\n        INSERT INTO raw.users(user_id, username, email, address, phone_number, created_at)\n        SELECT user_id, username, email, address, phone_number, created_at\n        FROM temp_users\n        WHERE temp_users.user_id NOT IN (SELECT user_id FROM raw.users);\n        DROP TABLE temp_users;"\n    ']
[2024-07-06T18:55:42.920+0000] {subprocess.py:86} INFO - Output:
[2024-07-06T18:55:42.949+0000] {subprocess.py:93} INFO - ERROR:  syntax error at or near "\"
[2024-07-06T18:55:42.949+0000] {subprocess.py:93} INFO - LINE 3:         \copy temp_users FROM stdin;
[2024-07-06T18:55:42.949+0000] {subprocess.py:93} INFO -                 ^
[2024-07-06T18:55:42.949+0000] {subprocess.py:93} INFO - ERROR:  invalid input syntax for type timestamp: " 1970-01-01 00:00:00
[2024-07-06T18:55:42.950+0000] {subprocess.py:93} INFO -  1970-01-01 00:00:00
[2024-07-06T18:55:42.950+0000] {subprocess.py:93} INFO -  1970-01-01 00:00:00"
[2024-07-06T18:55:42.950+0000] {subprocess.py:93} INFO - LINE 1: COPY  ( SELECT * FROM users WHERE created_at > ' 1970-01-01 ...
[2024-07-06T18:55:42.950+0000] {subprocess.py:93} INFO -                                                        ^
[2024-07-06T18:55:42.950+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-06T18:55:42.956+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-06T18:55:42.957+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=import_main_data, task_id=export_and_load_user_data, execution_date=20240706T040000, start_date=20240706T185542, end_date=20240706T185542
[2024-07-06T18:55:42.962+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 932 for task export_and_load_user_data (Bash command failed. The command returned a non-zero exit code 1.; 1834)
[2024-07-06T18:55:42.995+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-06T18:55:43.005+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
