[2024-06-27T22:35:47.516+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:35:47.526+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T13:50:00+00:00 [queued]>
[2024-06-27T22:35:47.529+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T13:50:00+00:00 [queued]>
[2024-06-27T22:35:47.529+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:35:47.534+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 13:50:00+00:00
[2024-06-27T22:35:47.536+0000] {standard_task_runner.py:63} INFO - Started process 1484 to run task
[2024-06-27T22:35:47.537+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T13:50:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp9_knw01z']
[2024-06-27T22:35:47.538+0000] {standard_task_runner.py:91} INFO - Job 102: Subtask generate_and_insert_data
[2024-06-27T22:35:47.554+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T13:50:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:35:47.587+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T13:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T13:50:00+00:00'
[2024-06-27T22:35:47.588+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:35:47.625+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:35:47.625+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:35:47.625+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:35:47.630+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T13:50:00+00:00, execution_date=20230101T135000, start_date=20240627T223547, end_date=20240627T223547
[2024-06-27T22:35:47.637+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:35:47.643+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:35:47.644+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:17:23.057+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:17:23.068+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T13:50:00+00:00 [queued]>
[2024-06-28T18:17:23.070+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T13:50:00+00:00 [queued]>
[2024-06-28T18:17:23.070+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:17:23.074+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 13:50:00+00:00
[2024-06-28T18:17:23.076+0000] {standard_task_runner.py:63} INFO - Started process 2377 to run task
[2024-06-28T18:17:23.077+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T13:50:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpjw3ffrnz']
[2024-06-28T18:17:23.078+0000] {standard_task_runner.py:91} INFO - Job 169: Subtask generate_and_insert_data
[2024-06-28T18:17:23.095+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T13:50:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:17:23.122+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T13:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T13:50:00+00:00'
[2024-06-28T18:17:23.123+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:17:23.180+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:17:23.180+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:17:23.180+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:17:23.180+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:17:23.181+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:17:23.185+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T13:50:00+00:00, execution_date=20230101T135000, start_date=20240628T181723, end_date=20240628T181723
[2024-06-28T18:17:23.220+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:17:23.227+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:17:23.227+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
