[2024-07-15T23:38:18.491+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-07-15T23:38:18.499+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-15T23:38:18.505+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-07-15T23:38:18.506+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-07-15T23:38:18.507+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [queued]> from DB
[2024-07-15T23:38:18.519+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-15T23:38:18.525+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-15T23:38:18.527+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-07-15T23:38:18.527+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-15T23:38:18.527+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [queued]>
[2024-07-15T23:38:18.527+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-15T23:38:18.531+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-15T23:38:18.532+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-07-15T23:38:18.532+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-15T23:38:18.533+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [queued]>
[2024-07-15T23:38:18.533+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2024-07-15T23:38:18.538+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): model.matt_demo.crm_performance> on 2024-07-15 23:31:56.990794+00:00
[2024-07-15T23:38:18.541+0000] {standard_task_runner.py:57} INFO - Started process 694 to run task
[2024-07-15T23:38:18.543+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_model_crm_sales', 'model.matt_demo.crm_performance', 'manual__2024-07-15T23:31:56.990794+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_models_crm_sales.py', '--cfg-path', '/tmp/tmp7qf47qd2']
[2024-07-15T23:38:18.543+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask model.matt_demo.crm_performance
[2024-07-15T23:38:18.544+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0xffff7ee0a550>]
[2024-07-15T23:38:18.581+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-07-15T23:38:18.584+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [running]> on host f934d9af8cb8
[2024-07-15T23:38:18.584+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 694)
[2024-07-15T23:38:18.584+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 694)
[2024-07-15T23:38:18.584+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-15T23:38:18.585+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [running]> from DB
[2024-07-15T23:38:18.609+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-07-15T23:38:18.610+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-07-15T23:38:18.636+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-15T23:38:18.644+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_model_crm_sales' AIRFLOW_CTX_TASK_ID='model.matt_demo.crm_performance' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T23:31:56.990794+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-15T23:31:56.990794+00:00'
[2024-07-15T23:38:18.644+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-07-15T23:38:18.644+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-07-15T23:38:18.645+0000] {bash.py:186} DEBUG - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_model_crm_sales' AIRFLOW_CTX_TASK_ID='model.matt_demo.crm_performance' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T23:31:56.990794+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-15T23:31:56.990794+00:00'
[2024-07-15T23:38:18.645+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-15T23:38:18.646+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            export DBT_SCHEMA=analysis_crm_sales &&\n            cd /opt/airflow/dbt &&\n            /home/airflow/.local/bin/dbt --no-write-json run --target dev --models crm_performance\n            ']
[2024-07-15T23:38:18.650+0000] {subprocess.py:86} INFO - Output:
[2024-07-15T23:38:19.710+0000] {subprocess.py:93} INFO - [0m23:38:19  Running with dbt=1.8.3
[2024-07-15T23:38:19.860+0000] {subprocess.py:93} INFO - [0m23:38:19  Registered adapter: ***=1.8.2
[2024-07-15T23:38:20.102+0000] {subprocess.py:93} INFO - [0m23:38:20  Found 6 models, 4 sources, 652 macros
[2024-07-15T23:38:20.103+0000] {subprocess.py:93} INFO - [0m23:38:20
[2024-07-15T23:38:20.153+0000] {subprocess.py:93} INFO - [0m23:38:20  Concurrency: 4 threads (target='dev')
[2024-07-15T23:38:20.153+0000] {subprocess.py:93} INFO - [0m23:38:20
[2024-07-15T23:38:20.158+0000] {subprocess.py:93} INFO - [0m23:38:20  1 of 1 START sql table model analysis_crm_sales.crm_performance ................ [RUN]
[2024-07-15T23:38:20.196+0000] {subprocess.py:93} INFO - [0m23:38:20  1 of 1 ERROR creating sql table model analysis_crm_sales.crm_performance ....... [[31mERROR[0m in 0.04s]
[2024-07-15T23:38:20.201+0000] {subprocess.py:93} INFO - [0m23:38:20
[2024-07-15T23:38:20.202+0000] {subprocess.py:93} INFO - [0m23:38:20  Finished running 1 table model in 0 hours 0 minutes and 0.10 seconds (0.10s).
[2024-07-15T23:38:20.202+0000] {subprocess.py:93} INFO - [0m23:38:20
[2024-07-15T23:38:20.203+0000] {subprocess.py:93} INFO - [0m23:38:20  [31mCompleted with 1 error and 0 warnings:[0m
[2024-07-15T23:38:20.203+0000] {subprocess.py:93} INFO - [0m23:38:20
[2024-07-15T23:38:20.203+0000] {subprocess.py:93} INFO - [0m23:38:20    Database Error in model crm_performance (models/crm_sales_data/analysis/crm_performance.sql)
[2024-07-15T23:38:20.203+0000] {subprocess.py:93} INFO -   invalid input syntax for type integer: "1C1I7A6R"
[2024-07-15T23:38:20.204+0000] {subprocess.py:93} INFO -   compiled Code at target/run/matt_demo/models/crm_sales_data/analysis/crm_performance.sql
[2024-07-15T23:38:20.204+0000] {subprocess.py:93} INFO - [0m23:38:20
[2024-07-15T23:38:20.204+0000] {subprocess.py:93} INFO - [0m23:38:20  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-07-15T23:38:20.715+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-15T23:38:20.716+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [running]> from DB
[2024-07-15T23:38:20.723+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-15T23:38:20.723+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [running]> from DB
[2024-07-15T23:38:20.724+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 2.196762
[2024-07-15T23:38:20.725+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-07-15T23:38:20.725+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=run_dbt_model_crm_sales, task_id=model.matt_demo.crm_performance, execution_date=20240715T233156, start_date=20240715T233818, end_date=20240715T233820
[2024-07-15T23:38:20.732+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-07-15T23:38:20.732+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 102 for task model.matt_demo.crm_performance (Bash command failed. The command returned a non-zero exit code 1.; 694)
[2024-07-15T23:38:20.752+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-15T23:38:20.785+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_model_crm_sales @ 2024-07-15 23:31:56.990794+00:00: manual__2024-07-15T23:31:56.990794+00:00, state:running, queued_at: 2024-07-15 23:31:57.100386+00:00. externally triggered: True>: 12 task(s)
[2024-07-15T23:38:20.785+0000] {dagrun.py:718} DEBUG - number of scheduleable tasks for <DagRun run_dbt_model_crm_sales @ 2024-07-15 23:31:56.990794+00:00: manual__2024-07-15T23:31:56.990794+00:00, state:running, queued_at: 2024-07-15 23:31:57.100386+00:00. externally triggered: True>: 3 task(s)
[2024-07-15T23:38:20.785+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.generate_dbt_docs manual__2024-07-15T23:31:56.990794+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-15T23:38:20.786+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.generate_dbt_docs manual__2024-07-15T23:31:56.990794+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=8, skipped=0, failed=0, upstream_failed=0, removed=0, done=8), upstream_task_ids={'test.matt_demo.crm_performance', 'test.matt_demo.crm_stg_sales_teams', 'model.matt_demo.crm_stg_accounts', 'test.matt_demo.crm_stg_sales_pipelines', 'model.matt_demo.crm_stg_sales_pipelines', 'model.matt_demo.crm_performance', 'model.matt_demo.crm_stg_products', 'test.matt_demo.crm_stg_products', 'model.matt_demo.crm_stg_sales_teams', 'test.matt_demo.crm_stg_accounts'}
[2024-07-15T23:38:20.786+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_model_crm_sales.generate_dbt_docs manual__2024-07-15T23:31:56.990794+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=8, skipped=0, failed=0, upstream_failed=0, removed=0, done=8), upstream_task_ids={'test.matt_demo.crm_performance', 'test.matt_demo.crm_stg_sales_teams', 'model.matt_demo.crm_stg_accounts', 'test.matt_demo.crm_stg_sales_pipelines', 'model.matt_demo.crm_stg_sales_pipelines', 'model.matt_demo.crm_performance', 'model.matt_demo.crm_stg_products', 'test.matt_demo.crm_stg_products', 'model.matt_demo.crm_stg_sales_teams', 'test.matt_demo.crm_stg_accounts'}
[2024-07-15T23:38:20.787+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.generate_dbt_docs manual__2024-07-15T23:31:56.990794+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-07-15T23:38:20.790+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.test.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-15T23:38:20.791+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.test.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=0, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.matt_demo.crm_performance', 'wait_for_dbt_init'}
[2024-07-15T23:38:20.792+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_model_crm_sales.test.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=0, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.matt_demo.crm_performance', 'wait_for_dbt_init'}
[2024-07-15T23:38:20.795+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.test.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-07-15T23:38:20.797+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-15T23:38:20.797714+00:00 and task will be retried at 2024-07-15T23:43:20.724443+00:00.
[2024-07-15T23:38:20.798+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-15T23:38:20.797714+00:00 and task will be retried at 2024-07-15T23:43:20.724443+00:00.
[2024-07-15T23:38:20.799+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_model_crm_sales.model.matt_demo.crm_performance manual__2024-07-15T23:31:56.990794+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-07-15T23:38:20.803+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
