[2024-07-06T22:21:30.862+0000] {taskinstance.py:1093} INFO - Dependencies not met for <TaskInstance: import_main_data.generate_transactions_sql scheduled__2024-07-06T13:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-07-06T22:21:30.863+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
